apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wg0cnomud-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wg0cnomud-java-springboot-gitops